import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:step_up_fuels/app/database/app_database.dart';
import 'package:step_up_fuels/features/expenses/data/repositories/expense_repository_impl.dart';
import 'package:step_up_fuels/features/expenses/domain/entities/expense.dart';
import 'package:step_up_fuels/features/purchases/data/repositories/purchase_repository_impl.dart';
import 'package:step_up_fuels/features/purchases/domain/entities/fuel_purchase.dart';
import 'package:step_up_fuels/features/purchases/domain/entities/fuel_purchase_item.dart';
import 'package:step_up_fuels/features/purchases/domain/entities/supplier.dart';

void main() {
  late AppDatabase db;
  late PurchaseRepositoryImpl purchaseRepository;
  late ExpenseRepositoryImpl expenseRepository;

  setUp(() {
    // 1. Initialize an in-memory database for clean, isolated test runs
    db = AppDatabase.forTesting(NativeDatabase.memory());
    purchaseRepository = PurchaseRepositoryImpl(db.purchasesDao);
    expenseRepository = ExpenseRepositoryImpl(db.expensesDao);
  });

  tearDown(() async {
    await db.close();
  });

  group('Purchases & Expenses Management Integration Tests', () {
    test('should save a supplier and retrieve it successfully', () async {
      // 1. Arrange: Create a mock supplier vendor
      final supplier = Supplier(
        id: 'supplier-1',
        supplierCode: 'SPL-001',
        name: 'Bharat Petroleum',
        contactPerson: 'Abhishek G',
        phone: '9876543210',
        isActive: true,
        createdBy: 'tester',
        createdAt: DateTime.now(),
        updatedBy: 'tester',
        updatedAt: DateTime.now(),
        version: 1,
      );

      // 2. Act: Save the supplier
      final saveRes = await purchaseRepository.saveSupplier(supplier);
      expect(saveRes.isSuccess, isTrue);

      // 3. Assert: Retrieve and verify
      final fetchRes = await purchaseRepository.getSuppliers();
      expect(fetchRes.isSuccess, isTrue);
      expect(fetchRes.dataOrThrow.length, 1);
      expect(fetchRes.dataOrThrow.first.name, 'Bharat Petroleum');
      expect(fetchRes.dataOrThrow.first.supplierCode, 'SPL-001');
    });

    test('should auto-generate serial number and log InventoryMovement when fuel purchase is saved', () async {
      // 1. Arrange: Prepare Supplier & Products
      final supplier = Supplier(
        id: 'supplier-2',
        supplierCode: 'SPL-002',
        name: 'HPCL',
        contactPerson: 'John D',
        phone: '9876543222',
        isActive: true,
        createdBy: 'tester',
        createdAt: DateTime.now(),
        updatedBy: 'tester',
        updatedAt: DateTime.now(),
        version: 1,
      );
      await purchaseRepository.saveSupplier(supplier);

      final purchase = FuelPurchase(
        id: 'purchase-1',
        purchaseNumber: 'PENDING', // Will be auto-generated by the repository concretion
        supplierId: 'supplier-2',
        supplierInvoiceNo: 'SUP-INV-9988',
        purchaseDate: DateTime.now(),
        subtotal: 1000.0,
        cgstAmount: 90.0,
        sgstAmount: 90.0,
        igstAmount: 0.0,
        totalAmount: 1180.0,
        paymentStatus: 'UNPAID',
        createdBy: 'tester',
        createdAt: DateTime.now(),
        updatedBy: 'tester',
        updatedAt: DateTime.now(),
        version: 1,
      );

      final item = FuelPurchaseItem(
        id: 'item-1',
        purchaseId: 'purchase-1',
        productId: 'product-diesel', // Mock ID
        description: 'High Speed Diesel',
        quantity: 200.0,
        unit: 'LTRS',
        rate: 5.0,
        taxableAmount: 1000.0,
        gstRate: 0.18,
        cgstRate: 0.09,
        sgstRate: 0.09,
        igstRate: 0.0,
        cgstAmount: 90.0,
        sgstAmount: 90.0,
        igstAmount: 0.0,
        totalAmount: 1180.0,
        sortOrder: 0,
      );

      // 2. Act: Save the purchase
      final saveRes = await purchaseRepository.savePurchase(purchase, [item]);
      expect(saveRes.isSuccess, isTrue);

      // 3. Assert: Verify purchase header was generated and auto-numbered
      final fetchRes = await purchaseRepository.getPurchaseById('purchase-1');
      expect(fetchRes.isSuccess, isTrue);
      expect(fetchRes.dataOrThrow.purchaseNumber, contains('PUR/'));
      expect(fetchRes.dataOrThrow.paymentStatus, 'UNPAID');

      // 4. Assert: Verify the hook created an InventoryMovement adding stock to Main Storage
      final movements = await db.select(db.inventoryMovements).get();
      expect(movements.length, 1);
      expect(movements.first.type, 'PURCHASE_IN');
      expect(movements.first.quantity, 200.0);
      expect(movements.first.referenceId, 'purchase-1');
      expect(movements.first.referenceType, 'PURCHASE');
      expect(movements.first.destinationLocationId, 'main-storage-terminal');
      expect(movements.first.sourceLocationId, isNull);
    });

    test('should save expense and generate serial numbers sequentially', () async {
      // 1. Arrange: Create mock expenses
      final expense1 = Expense(
        id: 'exp-1',
        expenseNumber: 'PENDING',
        category: 'OFFICE_EXPENSES',
        amount: 350.0,
        expenseDate: DateTime.now(),
        paymentMode: 'CASH',
        notes: 'Office stationary and folders purchase',
        createdBy: 'tester',
        createdAt: DateTime.now(),
        updatedBy: 'tester',
        updatedAt: DateTime.now(),
        version: 1,
      );

      final expense2 = Expense(
        id: 'exp-2',
        expenseNumber: 'PENDING',
        category: 'DRIVER_SALARY',
        amount: 25000.0,
        expenseDate: DateTime.now(),
        paymentMode: 'BANK_TRANSFER',
        notes: 'June salary payout',
        createdBy: 'tester',
        createdAt: DateTime.now(),
        updatedBy: 'tester',
        updatedAt: DateTime.now(),
        version: 1,
      );

      // 2. Act: Save both expenses
      final saveRes1 = await expenseRepository.save(expense1);
      final saveRes2 = await expenseRepository.save(expense2);
      expect(saveRes1.isSuccess, isTrue);
      expect(saveRes2.isSuccess, isTrue);

      // 3. Assert: Verify auto-generated expense numbers are sequential
      final fetchRes1 = await expenseRepository.getById('exp-1');
      final fetchRes2 = await expenseRepository.getById('exp-2');

      expect(fetchRes1.isSuccess, isTrue);
      expect(fetchRes2.isSuccess, isTrue);

      expect(fetchRes1.dataOrThrow.expenseNumber, contains('EXP/'));
      expect(fetchRes2.dataOrThrow.expenseNumber, contains('EXP/'));

      // Check increment sequence
      final no1 = fetchRes1.dataOrThrow.expenseNumber;
      final no2 = fetchRes2.dataOrThrow.expenseNumber;
      expect(no1, isNot(no2));
    });
  });
}
